CREATE PROC FI_SP_VerificaCliente
	@CPF varchar(15)
AS 
BEGIN
	DECLARE @SCRIPT NVARCHAR(MAX)
	
	SET @SCRIPT = 'SELECT COUNT(1) FROM CLIENTES WHERE CPF = @CPF'

	EXECUTE sp_executesql @SCRIPT, N'@CPF VARCHAR(15)', @CPF = @CPF
END
